# Generated by Django 3.2.4 on 2021-06-11 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examaltersys', '0002_alter_takeduty_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers_text', models.CharField(max_length=255)),
                ('answers_image', models.ImageField(blank=True, default=None, null=True, upload_to='answerimages')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='examaltersys.user_t')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='FreqQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('question_image', models.ImageField(blank=True, default=None, null=True, upload_to='questionimages')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='examaltersys.user_t')),
            ],
            options={
                'verbose_name': 'FrequentQuestion',
                'verbose_name_plural': 'FrequentQuestions',
            },
        ),
        migrations.CreateModel(
            name='QuesAnsRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='examaltersys.answers')),
                ('questions', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='examaltersys.freqquestions')),
            ],
            options={
                'verbose_name': 'QuesAnsRelationObject',
                'verbose_name_plural': 'QuesAnsRelationObjects',
            },
        ),
    ]
