# Generated by Django 3.2.4 on 2021-06-09 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_ID', models.CharField(max_length=30)),
                ('Course_name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100, null=True)),
                ('credits', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ('Course_ID',),
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=30)),
                ('day', models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('T', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday')], default='M', max_length=10)),
                ('Date', models.DateField(null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('slot', models.CharField(max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Exam Slot',
                'verbose_name_plural': 'Exam Slots',
                'ordering': ['Date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='examaltersys.course')),
                ('exam', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='examaltersys.exam')),
            ],
            options={
                'verbose_name': 'Exam Allocation',
                'verbose_name_plural': 'Exam Allocations',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_ID', models.CharField(max_length=30)),
                ('Block', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ('Room_ID',),
            },
        ),
        migrations.CreateModel(
            name='TakeDuty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='available', max_length=30, null=True)),
                ('reason', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('exam', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='examaltersys.examallocation')),
            ],
            options={
                'verbose_name': 'TakeDuty',
                'verbose_name_plural': 'TakeDuties',
            },
        ),
        migrations.CreateModel(
            name='User_T',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('examdutyofficer', 'EXAMDUTYOFFICER'), ('faculty', 'FACULTY'), ('admin', 'ADMIN')], default=None, max_length=30)),
                ('phno', models.CharField(max_length=10)),
                ('DOB', models.DateField(null=True)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Type',
                'verbose_name_plural': 'User Types',
            },
        ),
        migrations.CreateModel(
            name='TakeDutyCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_count', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='examaltersys.takeduty')),
            ],
            options={
                'verbose_name': 'TakeDutyCountObject',
                'verbose_name_plural': 'TakeDutyCountObjects',
            },
        ),
        migrations.AddField(
            model_name='takeduty',
            name='faculty',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='takers', to='examaltersys.user_t'),
        ),
        migrations.CreateModel(
            name='RoomAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='examaltersys.user_t')),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='examaltersys.room')),
            ],
            options={
                'verbose_name': 'Room Allocation',
                'verbose_name_plural': 'Room Allocations',
            },
        ),
        migrations.CreateModel(
            name='NotificationCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifycount', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='examaltersys.notification')),
            ],
            options={
                'verbose_name': 'TakeDutyCountObject',
                'verbose_name_plural': 'TakeDutyCountObjects',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='examaltersys.user_t'),
        ),
        migrations.CreateModel(
            name='FacultyCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_count', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='examaltersys.user_t')),
            ],
            options={
                'verbose_name': 'FacultyCountObject',
                'verbose_name_plural': 'FacultyCountObjects',
            },
        ),
        migrations.AddField(
            model_name='examallocation',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='examaltersys.room'),
        ),
        migrations.CreateModel(
            name='AssignDuty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigners', to='examaltersys.user_t')),
                ('exam', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='examaltersys.examallocation')),
            ],
            options={
                'verbose_name': 'AssignDuty',
                'verbose_name_plural': 'AssignDuties',
            },
        ),
    ]
