# Generated by Django 3.2.4 on 2021-06-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examaltersys', '0005_auto_20210612_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Monday', max_length=10),
        ),
        migrations.AlterField(
            model_name='takeduty',
            name='status',
            field=models.CharField(blank=True, default='Available', max_length=30, null=True),
        ),
    ]
