# Generated by Django 3.2.4 on 2021-06-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examaltersys', '0006_auto_20210612_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='day',
            field=models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('T', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday')], default='M', max_length=10),
        ),
    ]
