# Generated by Django 3.2.4 on 2021-06-13 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examaltersys', '0007_alter_exam_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomallocation',
            name='faculty',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='examaltersys.user_t'),
        ),
        migrations.AlterField(
            model_name='takeduty',
            name='faculty',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='takers', to='examaltersys.user_t'),
        ),
    ]
